apiVersion: v1
kind: ReplicationController
metadata:
 name: bees-redis
spec:
 replicas: 1
 selector:
  app: bees-redis
 template:
  metadata:
   labels:
    app: bees-redis
  spec:
   containers:
   - name: bees-redis
     image: redis
     ports:
     - containerPort: 6379
